In [2]:
import pandas as pd
import math
import numpy as np
import chardet as cde

In [3]:
math.factorial(5)

120

In [4]:
s = pd.Series([1,3,5, np.nan, 6 ,8 ])
print (s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
# Lendo os bytes do arquivo com chardet-cde para identificar qual enconding/utf do mesmo
with open  ("Bases/amazon.csv","rb") as f: 
    result = cde.detect(f.read(10000))
print(result["encoding"])

ISO-8859-1

In [6]:
# Estilo padrão para ler arquivos no panda, porém pode ter conflito de utf-8 ]
# df = pd.read_csv ("Bases/amazon.csv")

#Após leitura do arquivo estamos utilizando o chardet - cde para armazenar o resultado na variavel code_utf para converter o encoding automaticamente.
#Estamos utilizando tbm o separador , e o header = none para realizar o tratamento da base onde desconsiderados a primeira linha como 'coluna' = lendo como texto
code_utf = result["encoding"]
df = pd.read_csv ("Bases/amazon.csv", encoding=code_utf , sep = ',', header=None)

In [7]:
# Processamento para corrigir as colunas afinal um dos problemas é a virgula na separação
df = df[0].str.split(',', expand=True)

#  Remover aspas extras dos nomes das colunas
df.columns = df.iloc[0].str.replace('"','')
df = df[1:] # Remove a linha de cabeçalho original

# Reseta índice
df = df.reset_index(drop=True)

In [8]:
# Atribuindo nomes corretos para as colunas
df.colums = ['year','state', 'month', 'number', 'date']

# Converter tipos de dados
df['year'] = df['year'].astype(int)
df['number'] = pd.to_numeric(df['number'], errors='coerce')

C:\Users\pablo merissi\AppData\Local\Temp\ipykernel_11356\1390247621.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.colums = ['year','state', 'month', 'number', 'date']

In [9]:
df.shape
print(f"Temos {df.shape[0]} linhas e {df.shape[1]} colunas.")

Temos 6454 linhas e 5 colunas.

In [10]:
df.info

<bound method DataFrame.info of 0     year        state       month  number        date
0     1998       "Acre"   "Janeiro"     0.0  1998-01-01
1     1999       "Acre"   "Janeiro"     0.0  1999-01-01
2     2000       "Acre"   "Janeiro"     0.0  2000-01-01
3     2001       "Acre"   "Janeiro"     0.0  2001-01-01
4     2002       "Acre"   "Janeiro"     0.0  2002-01-01
...    ...          ...         ...     ...         ...
6449  2012  "Tocantins"  "Dezembro"   128.0  2012-01-01
6450  2013  "Tocantins"  "Dezembro"    85.0  2013-01-01
6451  2014  "Tocantins"  "Dezembro"   223.0  2014-01-01
6452  2015  "Tocantins"  "Dezembro"   373.0  2015-01-01
6453  2016  "Tocantins"  "Dezembro"   119.0  2016-01-01

[6454 rows x 5 columns]>

In [12]:
df.head(5)

0  year   state      month  number        date
0  1998  "Acre"  "Janeiro"     0.0  1998-01-01
1  1999  "Acre"  "Janeiro"     0.0  1999-01-01
2  2000  "Acre"  "Janeiro"     0.0  2000-01-01
3  2001  "Acre"  "Janeiro"     0.0  2001-01-01
4  2002  "Acre"  "Janeiro"     0.0  2002-01-01

In [14]:
#Criando lista para tratar as linhas da coluna state e month
limpar_aspas = ['state' , 'month']

#Removendo aspas das colunas
df[limpar_aspas] = df[limpar_aspas].apply(lambda x: x.str.replace ('"', ''))

In [17]:
df.head(5)

0  year state    month  number        date
0  1998  Acre  Janeiro     0.0  1998-01-01
1  1999  Acre  Janeiro     0.0  1999-01-01
2  2000  Acre  Janeiro     0.0  2000-01-01
3  2001  Acre  Janeiro     0.0  2001-01-01
4  2002  Acre  Janeiro     0.0  2002-01-01